server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthBook
    username: root
    password: 112233
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: api/v1
